#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $BINSPDT_USER WITH PASSWORD $BINSPDT_PASSWORD;
  CREATE DATABASE $BINSPDT_DB_WEBSITE;
  CREATE DATABASE $BINSPDT_DB_BINARY;
  GRANT ALL PRIVILEGES ON DATABASE $BINSPDT_DB_WEBSITE TO $BINSPDT_USER;
  GRANT ALL PRIVILEGES ON DATABASE $BINSPDT_DB_BINARY TO $BINSPDT_USER;
EOSQL
