version: '2.4'

services:
  postgres:
    container_name: postgres
    image: binspdt/postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      BINSPDT_USER: binspdt
      BINSPDT_PASSWORD: binspdt
      BINSPDT_DB_WEBSITE: binspdt_website
      BINSPDT_DB_BINARY: binspdt_binary

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  
  pgadmin:
    container_name: pgadmin
    image: fenglc/pgadmin4:alpine
    ports:
      - 5050:5050
    environment:
      DEFAULT_USER: pgadmin
      DEFAULT_PASSWORD: pgadmin
