# Generated by Django 2.0.5 on 2018-05-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleObject',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='binary.Module')),
                ('data', models.BinaryField()),
            ],
            options={
                'db_table': 'module_objects',
            },
        ),
    ]
