# Generated by Django 2.1.4 on 2018-12-14 06:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0002_moduleobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('module_1_id', models.IntegerField()),
                ('module_2_id', models.IntegerField()),
                ('method', models.CharField(max_length=32)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'module_analyses',
            },
        ),
    ]
