import Vue from 'vue'
import Vuetify, {
  VAlert,
  VContent,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VContainer,
  VDataTable,
  VDivider,
  VFlex,
  VForm,
  VIcon,
  VLayout,
  VList,
  VListTile,
  VListTileAction,
  VListTileAvatar,
  VListTileSubTitle,
  VListTileTitle,
  // VProgressCircular,
  VProgressLinear,
  VMenu,
  VNavigationDrawer,
  VRadio,
  VRadioGroup,
  VSelect,
  VSlideYReverseTransition,
  VSpacer,
  VTextField,
  VToolbar,
  VToolbarSideIcon,
  VToolbarTitle,
  VTooltip,
} from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',

  components: {
    VAlert,
    VContent,
    VBreadcrumbs,
    VBreadcrumbsItem,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VContainer,
    VDataTable,
    VDivider,
    VFlex,
    VForm,
    VIcon,
    VLayout,
    VList,
    VListTile,
    VListTileAction,
    VListTileAvatar,
    VListTileSubTitle,
    VListTileTitle,
    // VProgressCircular,
    VProgressLinear,
    VMenu,
    VNavigationDrawer,
    VRadio,
    VRadioGroup,
    VSelect,
    VSlideYReverseTransition,
    VSpacer,
    VTextField,
    VToolbar,
    VToolbarSideIcon,
    VToolbarTitle,
    VTooltip,
  },
})
