# Generated by Django 2.0.5 on 2018-05-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('architecture', models.CharField(max_length=32)),
                ('base_address', models.BigIntegerField()),
                ('exporter', models.CharField(max_length=256)),
                ('version', models.IntegerField()),
                ('md5', models.CharField(max_length=32)),
                ('sha1', models.CharField(max_length=40)),
                ('comment', models.TextField()),
                ('import_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
