# Generated by Django 2.0.5 on 2018-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0002_moduleobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleResultObject',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
            ],
            options={
                'db_table': 'module_result_objects',
            },
        ),
    ]
